### ISSUE TITLE
Bot matches non-darn words

### ISSUE THREAD

**Issue by doug-wade** [rithvikvibhu/reddit-darn-bot#3]
The regex is `/darn/gi`, so it also matches words like [Darnell](https://www.reddit.com/r/boottoobig/comments/8kxwb5/it_doesnt_taste_great_so_be_on_the_lookout/dzbowbn). It seems the count would be more correct if we checked for the word darn in isolation by checking for the [word boundary](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) before and after: `/\bdarn\b/gi`.

**Comment by rithvikvibhu** [comment]
Thanks @doug-wade for pointing it out!
You're right. I decided to use that as some people might call it by mentioning "darnbot" or saying "darnit" and wanted to count all of them. It might be better if the regex specifically searched for all variations.

**Comment by rithvikvibhu** [comment]
So I looked up the comments till now which _dont_ match "darn" with word boundaries and there are a lot of variations. Just a sample of what I found:
- darn
- darns
- darned
- darnation
- darnbot
- darnit
- goshdarn
- goshdarnit

And a lot more. So I think it's best to leave it as it is. Though maybe blacklist "NickDarnell" because there are ~5 comments which mention him as of now.
